### ISSUE TITLE
Perhaps migrate to nix-community?

### ISSUE THREAD

**Issue by surfaceflinger** [nix-community/browser-previews#8]
Hi!

I was planning on doing exactly the same thing but decided to use github search first and sort by recently updated. TYSM for this repo! 

For Firefox, we have https://github.com/nix-community/flake-firefox-nightly but it only includes nightlies. Perhaps it would be possible to merge both projects, include all Firefox editions and move this project to nix-community? I'd say that having browsers outdated even by a single day can be quite dangerous and sometimes nixos-unstable can take some time to update.
We would have this problem solved for both Chrome and Firefox this way.

**Comment by r-k-b** [comment]
Sure, I'd be open to moving this into nix-community.

**Comment by JohnRTitor** [comment]
I, too, support moving this over to nix-community :) Merging both projects aren't a bad idea, though personally I would like to see it seperated. If @r-k-b wants, I would have no reason to oppose a merger though :)

**Comment by r-k-b** [comment]
done: https://github.com/nix-community/browser-previews
